[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["Christian_Yemele <yemelechristian2@gmail.com>"]
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]